"""A dependency-free authenticated monitor, intentionally no inference controls."""
PAGE = r"""<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Astra Studio</title>
<style>body{font:15px system-ui;background:#101216;color:#edf1f5;margin:0;padding:36px;max-width:1300px;margin:auto}h1{font-size:25px}header{display:flex;justify-content:space-between;align-items:center}small,.muted{color:#a5acb9}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}.card{background:#191d24;border:1px solid #303744;border-radius:12px;padding:20px}strong{font-size:24px}p{line-height:1.7}.state{color:#8ce7bb}input,button{background:#232a35;color:inherit;border:1px solid #414b5b;padding:10px;border-radius:6px}#status{margin:24px 0}</style>
<header><div><h1>Astra Studio</h1><small>TensorFold · conversation memory</small></div><form id="login"><input id="key" type="password" placeholder="API key" autocomplete="off"><button>Connect</button></form></header>
<p id="status">Connect to view the server.</p><div id="slots" class="grid"></div>
<script>let token='',timer;const fmt=n=>n==null?'—':Number(n).toLocaleString(undefined,{maximumFractionDigits:1});const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelector('#login').onsubmit=e=>{e.preventDefault();token=document.querySelector('#key').value;document.querySelector('#key').value='';clearTimeout(timer);poll()};
async function poll(){try{const r=await fetch('/studio/metrics',{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!r.ok)throw Error('Server returned '+r.status);const d=await r.json();document.querySelector('#status').textContent=d.model+' · Up to '+d.parallel+' active generations · '+fmt(d.context)+' token window';document.querySelector('#slots').innerHTML=d.slots.map(s=>`<article class="card"><small>CONVERSATION ${s.slot}</small><h2 class="state">${esc(s.state)}</h2><strong>${fmt(s.state==='prefilling'?s.prompt_tps:s.decode_tps)}</strong> <small>tokens/sec · latest chunk / round</small><p>${fmt(s.prompt_tokens)} last-request prompt · ${fmt(s.generated_tokens)} generated<br>${fmt(s.checkpoint_tokens)} assigned checkpoint tokens<br>${fmt(s.shared_checkpoint_tokens)} shared prefix tokens<br>Assigned checkpoint RAM ${fmt((s.ram_bytes||0)/1073741824)} GiB · SSD ${fmt((s.ssd_bytes||0)/1073741824)} GiB</p><small>Last used: ${s.last_used?new Date(s.last_used*1000).toLocaleTimeString():'—'}${s.rate_at?' · reading '+fmt(Date.now()/1000-s.rate_at)+'s old':''}</small></article>`).join('')}catch(e){document.querySelector('#status').textContent=e.message+' · Last snapshot retained'}finally{timer=setTimeout(poll,document.hidden?5000:1000)}}
</script></html>"""
